import { describe, it, expect } from 'vitest';

import { isGeneratedFile } from './generated-file-check';

describe('isGeneratedFile', () => {
  describe('Layer 1: Path Patterns', () => {
    it('detects Swift Package Manager generated files', () => {
      expect(isGeneratedFile('Package.resolved').isGenerated).toBe(true);
    });

    it('detects lock files', () => {
      expect(isGeneratedFile('package-lock.json').isGenerated).toBe(true);
      expect(isGeneratedFile('yarn.lock').isGenerated).toBe(true);
      expect(isGeneratedFile('pnpm-lock.yaml').isGenerated).toBe(true);
      expect(isGeneratedFile('go.sum').isGenerated).toBe(true);
    });

    it('detects minified files', () => {
      expect(isGeneratedFile('jquery.min.js').isGenerated).toBe(true);
      expect(isGeneratedFile('style.min.css').isGenerated).toBe(true);
    });

    it('detects generated naming conventions', () => {
      expect(isGeneratedFile('user.generated.ts').isGenerated).toBe(true);
      expect(isGeneratedFile('api.gen.go').isGenerated).toBe(true);
      expect(isGeneratedFile('service.pb.go').isGenerated).toBe(true);
      expect(isGeneratedFile('schema.graphql.ts').isGenerated).toBe(true);
    });

    it('detects generated directories', () => {
      expect(isGeneratedFile('node_modules/package/index.js').isGenerated).toBe(true);
      expect(isGeneratedFile('dist/bundle.js').isGenerated).toBe(true);
      expect(isGeneratedFile('src/__generated__/query.ts').isGenerated).toBe(true);
    });

    it('returns false for regular files', () => {
      expect(isGeneratedFile('src/index.ts').isGenerated).toBe(false);
      expect(isGeneratedFile('README.md').isGenerated).toBe(false);
    });
  });

  describe('Layer 2: Universal Header Patterns', () => {
    it('detects @generated marker', () => {
      const lines = ['/**', ' * @generated', ' */'];
      expect(isGeneratedFile('src/unknown.ts', () => lines).isGenerated).toBe(true);
    });

    it('detects DO NOT EDIT marker', () => {
      const lines = ['// Code generated by tool. DO NOT EDIT.'];
      expect(isGeneratedFile('src/client.ts', () => lines).isGenerated).toBe(true);
    });

    it("detects 'Generated by' phrase", () => {
      const lines = ['# Generated by SomeTool'];
      expect(isGeneratedFile('config.yaml', () => lines).isGenerated).toBe(true);
    });
  });

  describe('Layer 3: Language-Specific Patterns', () => {
    it('detects Go specific patterns', () => {
      const lines = ['// Code generated by protoc-gen-go. DO NOT EDIT.'];
      expect(isGeneratedFile('message.pb.go', () => lines).isGenerated).toBe(true); // Hits path first actually

      // Try one that doesn't hit path
      const otherLines = ['// Code generated by Wire. DO NOT EDIT.'];
      expect(isGeneratedFile('wire_gen.go', () => otherLines).isGenerated).toBe(true);
    });

    it('detects TS/JS specific patterns', () => {
      const lines = ['/* generated using openapi-typescript-codegen */'];
      expect(isGeneratedFile('api.ts', () => lines).isGenerated).toBe(true);
    });

    it('detects Python specific patterns', () => {
      const lines = ['# Generated by Django'];
      expect(isGeneratedFile('migrations/001_initial.py', () => lines).isGenerated).toBe(true);
    });
  });

  describe('Lazy Evaluation', () => {
    it('does not call getHeaderLines if path match is found', () => {
      // We can't easily spy on a plain function passed as arg without a wrapper,
      // but we can pass a dummy function and ensure it's not strictly needed for the result

      // Actually simpler: if we pass a function that throws, it should NOT throw if path matches
      const throwFn = () => {
        throw new Error('Should not be called');
      };

      expect(isGeneratedFile('package-lock.json', throwFn).isGenerated).toBe(true);
    });
  });

  describe('False Positives', () => {
    it('does not mark CHANGELOG.md as generated even if it mentions markers', () => {
      const path = 'CHANGELOG.md';
      const content = [
        '# Changelog',
        '',
        '- Support for detecting files with @generated or DO NOT EDIT headers',
      ];
      const getHeaderLines = () => content;

      const result = isGeneratedFile(path, getHeaderLines);
      expect(result.isGenerated).toBe(false);
    });

    it('does not mark other markdown files as generated', () => {
      const path = 'docs/guide.md';
      const content = ['# User Guide', 'Use the @generated annotation to mark files.'];
      const getHeaderLines = () => content;

      const result = isGeneratedFile(path, getHeaderLines);
      expect(result.isGenerated).toBe(false);
    });
  });
});
